<<<<<<< Updated upstream
# Generated by Django 4.0.3 on 2022-07-23 23:06
=======
# Generated by Django 4.0.3 on 2022-07-22 16:58
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=70, unique=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=25, unique=True)),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(blank=True, max_length=255)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(null=True)),
                ('fecha_hora_fin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_normal', models.ImageField(upload_to='img/productos')),
                ('imagen_miniatura', models.ImageField(upload_to='img/productos')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_personalizado', models.ImageField(blank=True, upload_to='img/ productos/personalizado')),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=30, unique=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=30, unique=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion_Producto',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('puntos_aplicados', models.IntegerField(null=True)),
                ('aplica_puntos', models.BooleanField(default=False)),
                ('cantidad_puntos', models.IntegerField(null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('descuento', models.FloatField(default=0.0)),
                ('caducidad_puntos', models.DateTimeField(blank=True, null=True)),
                ('caducidad_oferta', models.DateTimeField(blank=True, null=True)),
                ('envio_gratis', models.BooleanField(default=False)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_value', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=150, unique=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
    ]
