# Generated by Django 4.0.3 on 2022-07-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=70)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=25)),
                ('describe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_marca', models.CharField(max_length=30)),
                ('es_elimidado', models.BooleanField(default=False)),
                ('id_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_value', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=30)),
                ('es_elimidado', models.BooleanField(default=False)),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.marca')),
            ],
        ),
    ]
