# Generated by Django 4.0.3 on 2022-07-19 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(blank=True, max_length=255)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('fecha_hora_inicio', models.DateTimeField(null=True)),
                ('fecha_hora_fin', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField(unique=True)),
                ('Empleado_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_normal', models.ImageField(blank=True, upload_to='img/productos')),
                ('img_miniatura', models.ImageField(blank=True, upload_to='img/productos')),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=150, unique=True)),
                ('es_elimidado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='dispositivo',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre_estado',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre_marca',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre_modelo',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_value',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='ProductoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('es_elimidado', models.BooleanField(default=False)),
                ('client_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispositivo_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.dispositivo')),
                ('marca_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.marca')),
                ('modelo_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.modelo')),
                ('precio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.precioproductopersonalizado')),
                ('tipo_producto_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.tipo_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(null=True)),
                ('aplica_puntos', models.BooleanField(default=False)),
                ('cantidad_puntos', models.IntegerField(null=True)),
                ('en_oferta', models.BooleanField(default=False)),
                ('descuento', models.FloatField(default=0.0)),
                ('caducidad_puntos', models.DateTimeField(blank=True, null=True)),
                ('caducidad_oferta', models.DateTimeField(blank=True, null=True)),
                ('envio_gratis', models.BooleanField(default=False)),
                ('es_elimidado', models.BooleanField(default=False)),
                ('dispositivo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.dispositivo')),
                ('evento_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.evento')),
                ('marca_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.marca')),
                ('modelo_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.modelo')),
                ('presentacion_Producto_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.presentacion_producto')),
                ('tipo_producto_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.tipo_producto')),
            ],
        ),
        migrations.AddField(
            model_name='precioproductopersonalizado',
            name='dispositivo_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.dispositivo'),
        ),
    ]
