# Generated by Django 4.0.3 on 2022-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion_producto',
            name='id',
            field=models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
