# Generated by Django 4.0.3 on 2022-07-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_validado',
            field=models.BooleanField(default=False),
        ),
    ]
