# Generated by Django 4.0.3 on 2022-07-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_es_validado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contrato',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='origen_pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
